### ISSUE TITLE
Print only modules which require updates

### ISSUE THREAD

**Issue by dawidmalina** [keilerkonzept/terraform-module-versions#12]
It would be good if we could skip modules which are up to date and print only modules which require attention.

**Comment by jack17529** [comment]
@dawidmalina So you want to say that when `"nonMatchingUpdate": true` then do not print it?

**Comment by dawidmalina** [comment]
@jack17529 - Yes, it shall omit module for any possible: `constraintUpdate`, `matchingUpdate`, `nonMatchingUpdate`.

**Comment by jack17529** [comment]
@dawidmalina I have sent a PR https://github.com/keilerkonzept/terraform-module-versions/pull/13  
Although if we want to only see the updates strictly according to the constraints and not the overall update, I can submit another PR for that. As I would have to add a new flag and make some changes, it would be better if the repository's owner gives me permission for that.

**Comment by sgreben** [comment]
also addressed in #25 :)
