### ISSUE TITLE
Executable is compatible only with alpine

### ISSUE THREAD

**Issue by dawidmalina** [keilerkonzept/terraform-module-versions#27]
Executable is compatible only with alpine (musl). When you run this on ubuntu it will not work:

```
terraform-module-versions
bash: terraform-module-versions: No such file or director
```

The problem is related to dynamic linking:

```
ldd /usr/bin/terraform-module-versions
	linux-vdso.so.1 (0x00007ffc517bc000)
	libc.musl-x86_64.so.1 => not found
```

We should switch to static linking similar to what terraform does:

```
ldd /usr/bin/terraform
	not a dynamic executable
```

**Comment by sgreben** [comment]
good catch, thanks! & have a good NYE tomorrow :)
