### ISSUE TITLE
Terraform 0.13-0.15 & 1.0

### ISSUE THREAD

**Issue by infogulch** [keilerkonzept/terraform-module-versions#57]
Hi! I'm curious what kind of work it would require to add support for newer versions of terraform.

This appears related to #55

**Comment by sgreben** [comment]
Actually those versions are already supported - the `terraform-config-inspect` package (https://github.com/hashicorp/terraform-config-inspect) is the one that would limit the supported config syntax version range & that dependency is up-to-date :)
